from typing import Any

from rich.markdown import Markdown as Markdown
from rich.syntax import Syntax as Syntax

def load_all_modules(mod) -> list[tuple[str, Any]]: ...
def is_standard_lib(module): ...
def get_root_module(module): ...
def is_imported(module, obj): ...
def get_full_name(obj): ...
def collect_info(obj: Any, depth: int = 1, current_depth: int = 0, signatures: bool = True, docs: bool = False, code: bool = False, imports: bool = False) -> dict[str, Any]: ...
def render_dict(members_dict: dict[str, Any], indent: int = 0) -> None: ...
def get_info(module, depth: int = 1, signatures: bool = True, docs: bool = True, code: bool = False, imports: bool = False) -> dict[str, Any]: ...
def inspect_library(module_or_class, depth, signatures: bool = True, docs: bool = True, code: bool = False, imports: bool = False, all: bool = False, markdown: bool = False): ...
def inspect_repo(repo_path, depth, signatures, docs, code, imports, all): ...
def inspect_cli(module_or_class, depth, sigs, docs, code, imports, all, markdown: bool = False): ...
