from io import StringIO as StringIO
from rich.markdown import Markdown as Markdown
from rich.syntax import Syntax as Syntax

def cli(module_or_class, depth, sigs, docs, code, imports, all, markdown): ...
def generate_markdown(result, sigs, docs, code): ...
def generate_markdown_section(name, info, sigs, docs, code, level: int = 2): ...
def generate_panels(console, result, sigs, docs, code) -> None: ...
def generate_panel_content(name, info, sigs, docs, code): ...
